### PR TITLE
Add path for getting JWTs for API access

### PR DESCRIPTION
**Pull request by LachlanStuart**

### CODE REVIEW

**Comment by intsco** [comment]
@LachlanStuart can I ask you to merge rel-v0.10 into master? I can't do it as there are conflicts

**Comment by LachlanStuart** [comment]
@intsco Will do

**Comment by intsco** [comment]
@LachlanStuart, btw, it doesn't work if a user logged in via Google

> Please log in before accessing this page

**Comment by LachlanStuart** [comment]
@intsco Ah, I see why: https://github.com/METASPACE2020/sm-webapp/pull/50/files#diff-78c12f5adc1848d13b1c6f07055d996eR253

`req.user` is an object if the user is logged in through Google, and a string if they're logged in through passwordless. Ideally this wouldn't be ambiguous, but I'll hold off on cleaning it up until we've had the discussion on whether to move the user database into the GraphQL project.

I won't make a hotfix as there is a workaround (using login by email) and this isn't a critical feature.

**Pull request merged**
